### ISSUE TITLE
What does this do?

### ISSUE THREAD

**Issue by ZyanKLee** [exeldro/obs-audio-monitor#1]
hey Exeldro,

thanks for your great OBS plugins. Can you show us how this plugin looks in OBS? Or at least explain with a little more detail what it does and which problems it solves?

best regards

**Comment by exeldro** [comment]
It allows you to put the audio of a OBS source to an audio device by adding the Audio Monitor filter on the Source in OBS Studio.
This can be useful in different use cases:
- monitoring a source on multiple devices
- monitoring audio without the delays of syncing to video
- separate monitoring audio levels per source and device

**Comment by ZyanKLee** [comment]
Great, thanks for the explanation. That seems really useful if one does not want to go through the hassle of setting up JACK (or similar tools for Windows/MacOS) just for the purpose of audio monitoring.

**Comment by exeldro** [comment]
At the moment it is Windows only. I am planning on adding Linux and MacOS support later.

**Comment by ZyanKLee** [comment]
I'll close this issue, as the explanation is now in the readme.
