### ISSUE TITLE
AdvanceAudioProperties Crashes

### ISSUE THREAD

**Issue by ATLTVHEAD** [exeldro/obs-audio-monitor#10]
I experienced obs crashing anytime I opened the advanced audio properties. Windows 64 bit, Audio monitor version 0.3.2. I also just updated to obs websockets 4.9 release, so I do not know if it is due some weird interaction there.

**Comment by ATLTVHEAD** [comment]
I specifically installed it with the windows installer. After deleting the files and installing them with the zip, everything is working again.

**Comment by exeldro** [comment]
There should be no difference between the installer and manual install. Can you provide a crash log?

**Comment by ATLTVHEAD** [comment]
Unfortunately, no crash log is created. Only half of the obs log is created before it cuts off.

**Comment by ATLTVHEAD** [comment]
I am still not sure what the problem was with release 3, but I no longer have crashes with release 5. I'm closing this.
