### ISSUE TITLE
Missing 'Output Slider' locales

### ISSUE THREAD

**Issue by COOLIGUAY** [exeldro/obs-audio-monitor#14]
Translations for Output Slider are not displayed.

French locale:

![Captura locale FR](https://user-images.githubusercontent.com/55640387/108600446-8abf9780-7397-11eb-82af-bd6a3dd4b011.PNG)

Spanish locale:

![Captura locale ES](https://user-images.githubusercontent.com/55640387/108600447-8c895b00-7397-11eb-93da-2b91ba283293.PNG)

**Comment by exeldro** [comment]
fixed in version 0.6.1
