### ISSUE TITLE
Feature Request: Use OBS output settings for Track names

### ISSUE THREAD

**Issue by lebaston100** [exeldro/obs-audio-monitor#15]
It would be nice if the audio track name in the mixer dock would get pulled from the obs audio output settings in case the setting is not empty.

![image](https://user-images.githubusercontent.com/26111114/108600831-88f6d380-7399-11eb-8806-cf14d64ee5aa.png)

**Comment by exeldro** [comment]
I like that idea, will try to add that

**Comment by exeldro** [comment]
You can find the first test build here:
https://github.com/exeldro/obs-audio-monitor/actions/runs/584860412

**Comment by lebaston100** [comment]
Tested earlier with run 584795581 and it seems to work so far.
Only thing i could find is that you need to either restart obs or re-add the track to update the label in the mixer. Personally i have no problem with that.

**Comment by exeldro** [comment]
Yeah I have not found a trigger or event when the configuration is changed yet.
An other workaround is switching profiles, that should load the names from the new profile.

**Comment by lebaston100** [comment]
Then i guess as long as there is no settings changed event from obs it will stay like that. As mentioned i have no problem with that as that's something that shouldn't really change that often inside a profile. Otherwise it seems to work perfectly fine.

**Comment by exeldro** [comment]
ok, releasing it with version 0.6.1 in a moment
