### ISSUE TITLE
Master Mixer (from pvkiet) and control volume on Track1-6

### ISSUE THREAD

**Issue by Trouffman** [exeldro/obs-audio-monitor#35]
**Goal**
Ability to control volume on an OBS Audio Track.
Ability to monitor this audio Track level. (already the case today, this include suggestion for improvment)

**Context**
One of the feature that is totally missing from OBS ( or this plugin is a way to monitor audio per track or input quickly without going to the advanced audio properties).

One of the great integration to fix this is a work by pvkiet for the OBS Music Edition, but he recently announced that he is dropping the project (he was doing a full fork rather than simply a plugin).

I suggest to implement the following ideas :
- Headphone Icon to quikly enable / disable audio monitoring onthe "Monitoring devices" set in the settings.
> this is a better implementation than proposed at : #22 
> See #39 for more details on this specific use-case.

- Allow for direct volume adjustement on the track 1-6
(I don't think the other features on the master mixer are necessary)

![Untitled](https://user-images.githubusercontent.com/2151317/144726293-54a844cd-cdf8-4f07-afad-bc8a4627c18b.png)

Reference of the project from pvkiet : https://github.com/pkviet/obs-studio/wiki/Master-Mixer-and-Inputs-Mixer

Note : This is linked to #40  for UI impact of adding the output slider for this feature

**Comment by Trouffman** [comment]
OP edited for clarity and title adjsuted in accordance.

**Comment by exeldro** [comment]
As far as I know obs has no way for plugins to set the volume per output track. I think this would require changes to OBS itself.
So only the monitoring volume can be changed from this plugin

**Comment by Trouffman** [comment]
That would explain why pvkiet did a Fork for this feature.
Closing this issue for now.

Reason for closing : No volume control per track available in OBS.

**Comment by luckyabsoluter** [comment]
I really need this feature.

I recorded a long video...
and then.. OH! No audio!

If "track" exist, "monitor" have to exist, of course...
