### ISSUE TITLE
Add tags and Linux compatibility

### ISSUE THREAD

**Issue by maxdrfr** [exeldro/obs-audio-monitor#4]
Hi @exeldro !

What a great project again ! I like very all your repos, thank you !

Please, can you add tags when you push commits on all your repos please ? It's more easy to seek and follow versions.
And, for obs-audio-monitor, I builded for Linux and the plugin recognize pulseaudio and find sink devices, do you think it's very incompatible ?

Thanks.

**Comment by exeldro** [comment]
At the moment the plugin only supports Windows and Mac, I have not looked into pulseaudio yet, but it should be possible to make. I have not got a linux environment setup at the moment, so it will take me some time.

**Comment by tytan652** [comment]
The problem with Linux is that there is PulseAudio and JACK sources for OBS (and maybe PipeWire in the future)

**Comment by philippejadin** [comment]
A linux version would be great indeed!

**Comment by Solander** [comment]
Definitely a Linux version would be amazing! Been recommended this plugin, but sadly, I cannot use it at the moment. :/

**Comment by maxdrfr** [comment]
hi, is there any devs who can bring a linux support please, it will be very great !

**Comment by hasrack** [comment]
You can also check out pipewire. It's the new audio and video subsystem for Linux and is aiming to replace both pulseaudio and Jack in the future.

https://venam.nixers.net/blog/unix/2021/06/23/pipewire-under-the-hood.html

https://docs.pipewire.org/

**Comment by maxdrfr** [comment]
There are still a lot of problems with pipewire that scare me.
I use pulseaudio with https://github.com/futpib/pagraphcontrol
or PA bridges for JACK and https://github.com/rncbc/qjackctl.

As this ticket is not a issue but an evolution request, I close it.
You can follow: https://github.com/exeldro/obs-audio-monitor/pull/5 and https://github.com/exeldro/obs-audio-monitor/pull/28
