### ISSUE TITLE
Memory leaks on fresh OBS 27.2 Installation

### ISSUE THREAD

**Issue by WizardCM** [exeldro/obs-audio-monitor#47]
Reproduction steps:

1. Download & install a fresh copy of OBS Studio 27.2.0 (or use the zip version) in portable mode
2. Load then close OBS
3. 0 memory leaks
4. Install the ZIP version of this plugin
5. Load then close OBS
6. 2 memory leaks

These 2 leaks appear with or without the dock visible, with a fully vanilla configuration.

In summary:
- 2 leaks in default Simple Output mode (1 for each of the default audio sources)
- 18 leaks after switching to Advanced Output mode (number of enabled tracks in Settings -> Output does not matter)
  - down to 17 if Mic/Aux is Disabled in Settings

Log: [2022-02-18 22-29-58.txt](https://github.com/exeldro/obs-audio-monitor/files/8096733/2022-02-18.22-29-58.txt)

Noticed when trying to track down leaks in my main installation. I'm personally seeing 31 leaks from this plugin there, likely due to source count.

**Comment by exeldro** [comment]
this should be fixed by https://github.com/exeldro/obs-audio-monitor/commit/bfbf4ea66561a082603a3b668973f7ccd522bd4a
download and test the build from here:
https://github.com/exeldro/obs-audio-monitor/actions/runs/1868886892

**Comment by WizardCM** [comment]
Confirmed - no more memory leaks on my side. Thanks!
