### ISSUE TITLE
Audio Monitor Issues in v28

### ISSUE THREAD

**Issue by KyleMcCarley** [exeldro/obs-audio-monitor#62]
Since updating to OBS 28, sounds played through the Audio Monitor filter seem to get very choppy whenever the volume slider is adjusted. And I haven't identified what else, specifically, causes it, but it sometimes happens without adjusting the volume. Restarting OBS or deleting and re-adding the filter temporarily fixes the problem, but only temporarily. What's worse is that any stuttering that's audible to me through the Audio Monitor filter appears to also be present in the outgoing stream.

In the process of troubleshooting another, seemingly unrelated, issue with the update to v28, I discovered via WinDbg that this plugin is constantly throwing errors that link to something along the lines of "avcore\audiocore\client\audioclient\mmdeviceactivator.cpp(279)\AUDIOSES.DLL!00007FF9B74C6431."

**Comment by felippenardi** [comment]
I'm experiencing this as well

**Comment by softwareitcounts** [comment]
Have the same issue with v27 and v28. I think it may be to do with the new windows 22H2 update. Also every time windows updates it breaks the audio and i have to select my headphones again on the filter. Very frustrating.

**Comment by softwareitcounts** [comment]
issue now fixed with version 0.8.2 and OBS 28
