### ISSUE TITLE
how should i uninstall the package on macOS?

### ISSUE THREAD

**Issue by faelp22** [exeldro/obs-audio-monitor#63]
I installed it on my macbook, but now I don't need it anymore and I would like to remove it, could you help me?

**Comment by felippenardi** [comment]
Would also like to know

**Comment by jonatan-ivanov** [comment]
It would be great to document this.

**Comment by jonatan-ivanov** [comment]
Thanks, I also found `plugin_config/audio-monitor`, I guess that could be removed to so:
```bash
rm -rf ~/Library/Application\ Support/obs-studio/plugins/audio-monitor.plugin/
rm -rf ~/Library/Application\ Support/obs-studio/plugin_config/audio-monitor/
```
