### ISSUE TITLE
Audio glitch with cause and replication steps.

### ISSUE THREAD

**Issue by jorge77401** [exeldro/obs-audio-monitor#65]
I know this has been reported, but I don't know how to add a reference to that issue, sorry?

Since version 0.7.1 there is a "glitch" that has been driving me crazy, and that is crackling noise and distortion under certain circumstances.

Steps to replicate:
1 - Use the Move transition plugin.
2 - Generate a filter that raises the volume to 100% with a duration of 2300 ms.
3 - Generate a filter that lowers the volume to 0% with a duration of 2300 ms.
4 - Activate the filters randomly without letting the previous one end.

The glitch only occurs when there are two transitions simultaneously on the same audio source.

It is only a matter of time before the glitch occurs; the audio will start to distort and the slider movement will stop being fluid, it will also increase the CPU usage, and the only way to solve this glitch is to restart OBS, it is worth clarifying that the audio distortion is also visible in recordings and live performances.

The only way I have found to avoid the problem is to use version 0.7.0 together with OBS 27.2.4, where curiously it does not occur, no matter how much the simultaneous fade is forced.

I would be very grateful if this problem could be examined as it is a bug that can potentially break a whole recording or live; thank you very much.

**Comment by exeldro** [comment]
This should be fixed with version 0.8.2
