### ISSUE TITLE
The order in which the options are checked in the dock shows different sources

### ISSUE THREAD

**Issue by COOLIGUAY** [exeldro/obs-audio-monitor#7]
Depends on the order in which the options are checked, different sources are shown.

If you check Output Slider first and Only Active later all active sources are displayed.

![Captura01](https://user-images.githubusercontent.com/55640387/106368118-9cd58980-6347-11eb-911d-2b08fc5c8792.PNG)

But if you check Only Active first and Output Slider later only the filtered source are displayed.

![Captura02](https://user-images.githubusercontent.com/55640387/106368119-9e9f4d00-6347-11eb-9ac9-61ef122f8625.PNG)

**Comment by exeldro** [comment]
that should be fixed in this version:
https://github.com/exeldro/obs-audio-monitor/actions/runs/524858843

**Comment by COOLIGUAY** [comment]
Now if you check Only Active first and Output Slider later all active and not active sources are displayed.

![Captura03](https://user-images.githubusercontent.com/55640387/106378735-53b52200-63a7-11eb-8780-3b4bd90e63d8.PNG)

**Comment by exeldro** [comment]
Ok, next try, new version building here:
https://github.com/exeldro/obs-audio-monitor/actions/runs/524955009

**Comment by COOLIGUAY** [comment]
Perfect! It works.

I have tried to leave only Output Slider checked, close OBS and open it again.

The plugin starts as if Only Active were checked.

![Captura04](https://user-images.githubusercontent.com/55640387/106379836-ed340200-63ae-11eb-929e-8fdd777a0480.PNG)

Also, desktop audio, mic and twitch vod plugin are not displayed.

Then, if you uncheck and check it again works as expected.

![Captura05](https://user-images.githubusercontent.com/55640387/106379976-a8f53180-63af-11eb-901c-75ef72fcb649.PNG)

"Audio del escritorio" = Desktop Audio  - Sorry!

**Comment by exeldro** [comment]
Thank you for the testing and the bug report, it should be fixed in this version:
https://github.com/exeldro/obs-audio-monitor/actions/runs/525064193

**Comment by COOLIGUAY** [comment]
Ty! Works fine now.
Glad to help and thanks for all your incredible work!

**Comment by exeldro** [comment]
Released version 0.2.0 with the fixes
