### ISSUE TITLE
this plugin gets crashed with touch portal

### ISSUE THREAD

**Issue by azamet90** [exeldro/obs-audio-monitor#70]
just try to connect to websocket with touch portal to obs and it will gets crashed. if not, close and reopen it; it will gets crashed endless.

**Comment by azamet90** [comment]
edit: also autmn vertigal plugin together is maybe causing this problem which is im not sure but if it is still not crashes, just install that plugin too.

**Comment by Tyr808** [comment]
I'm also getting the same crash but with SAMMI, which is the same kind of program as touch portal and uses OBS websockets.

If it's possible to set Touch Portal to not automatically connect, see if both programs can run at the same time. On my end everything is fine until I connect SAMMI to OBS via OBS websockets and everything instantly crashes and OBS won't even leave a crash log.

I'm thinking there is an issue with websockets and this plugin at the moment.

**Comment by ToTXR4Y** [comment]
Same issue - see: https://github.com/exeldro/obs-audio-monitor/issues/72

**Comment by exeldro** [comment]
I made a fix, can you test if it works for you?
https://github.com/exeldro/obs-audio-monitor/actions/runs/5783088154
at the bottom of that page you should be able to download a test version when you are logged in on GitHub

**Comment by exeldro** [comment]
Fixed with release 0.8.3
