### ISSUE TITLE
Crash when scrolling down with the mouse wheel in the dock

### ISSUE THREAD

**Issue by COOLIGUAY** [exeldro/obs-audio-monitor#8]
I tried with a new scene collection, on the Audio Monitor dock:

-Show Track 1 in Outputs 
-Scroll down with the mouse wheel
-OBS crashes

![DI9YSYVkPD](https://user-images.githubusercontent.com/55640387/106952659-af7a0500-6731-11eb-8368-f043135aa7b8.gif)

https://obsproject.com/logs/ptLaG0zHIYOhMOH-

It has also crashed without doing this specifically but it is the easiest way i have found to reproduce the issue.

**Comment by COOLIGUAY** [comment]
Another way to crash.

-Create a new scene collection
-Apply an Audio Monitor filter to the Desktop Audio
-Set the device
-Restart OBS
-The Desktop Audio is displayed twice in the dock.

![image](https://user-images.githubusercontent.com/55640387/106959173-9d509480-673a-11eb-9083-eeebc1962c30.png)

-Close OBS
-OBS crashes

**Comment by exeldro** [comment]
The first crash should be fixed in this build:
https://github.com/exeldro/obs-audio-monitor/actions/runs/539532625
The second crash I have not been able to reproduce yet.
I don't get my desktop audio double in the audio monitor dock.

**Comment by COOLIGUAY** [comment]
First crash ok here too, great!

For the second i have tried again.

To reproduce it is necessary that no track output is showing.

![image](https://user-images.githubusercontent.com/55640387/107047863-953f3600-67c8-11eb-8c6b-a13ac22b2637.png)
(This screenshot is from before the bug)

With one track output it works fine, no duplicated audio sources.

**Comment by exeldro** [comment]
the second bug should also be fixed, can you test if it works correct for you?

**Comment by COOLIGUAY** [comment]
Perfectly fixed with v.0.3.4, amazing work!
