### ISSUE TITLE
Crash on Windows 11 with OBS 30.1.0 and audio monitor

### ISSUE THREAD

**Issue by alxmedic** [exeldro/obs-audio-monitor#84]
Once again tried to use your awesome audio monitor in OBS to output processed stream audio to Wave Link as guest audio (mix minus) and several issues presented with audio monitor installation. 

1. old config.json file had a no longer present windows audio device from previous install of this plugin. Once I realized the issue. Deleting old config file. Manually uninstalled audio monitor and Installed audio monitor using windows installer. This presented with fresh install with no options enabled. Awesome. Setup audio device to output Track 6 and seemed to work flawlessly until I checked the OBS log file...  

2. OBS Log file indicating missing values for "meterThickness" and "meterFontScaling"

09:47:08.196: [Audio Monitor] loaded version 0.8.5
09:47:08.215: VolumeMeter(0x19c5d34fc30)  does not have a property named  "meterThickness"
09:47:08.215: VolumeMeter(0x19c5d34fc30)  does not have a property named  "meterFontScaling"
09:47:08.215: VolumeMeter(0x19c58976250)  does not have a property named  "meterThickness"
09:47:08.215: VolumeMeter(0x19c58976250)  does not have a property named  "meterFontScaling"
09:47:08.216: VolumeMeter(0x19c58b7ab70)  does not have a property named  "meterThickness"
09:47:08.216: VolumeMeter(0x19c58b7ab70)  does not have a property named  "meterFontScaling"
09:47:08.216: VolumeMeter(0x19c588f8de0)  does not have a property named  "meterThickness"
09:47:08.216: VolumeMeter(0x19c588f8de0)  does not have a property named  "meterFontScaling"
09:47:08.216: VolumeMeter(0x19c5cde0b30)  does not have a property named  "meterThickness"
09:47:08.216: VolumeMeter(0x19c5cde0b30)  does not have a property named  "meterFontScaling"
09:47:08.216: VolumeMeter(0x19c5d336ca0)  does not have a property named  "meterThickness"
09:47:08.216: VolumeMeter(0x19c5d336ca0)  does not have a property named  "meterFontScaling"
09:47:08.218: VolumeMeter(0x19c5d34fc30)  does not have a property named  "meterThickness"
09:47:08.218: VolumeMeter(0x19c5d34fc30)  does not have a property named  "meterFontScaling"
09:47:08.218: VolumeMeter(0x19c58976250)  does not have a property named  "meterThickness"
09:47:08.218: VolumeMeter(0x19c58976250)  does not have a property named  "meterFontScaling"
09:47:08.219: VolumeMeter(0x19c58b7ab70)  does not have a property named  "meterThickness"
09:47:08.219: VolumeMeter(0x19c58b7ab70)  does not have a property named  "meterFontScaling"
09:47:08.219: VolumeMeter(0x19c588f8de0)  does not have a property named  "meterThickness"
09:47:08.219: VolumeMeter(0x19c588f8de0)  does not have a property named  "meterFontScaling"
09:47:08.219: VolumeMeter(0x19c5cde0b30)  does not have a property named  "meterThickness"
09:47:08.219: VolumeMeter(0x19c5cde0b30)  does not have a property named  "meterFontScaling"
09:47:08.220: VolumeMeter(0x19c5d336ca0)  does not have a property named  "meterThickness"
09:47:08.220: VolumeMeter(0x19c5d336ca0)  does not have a property named  "meterFontScaling"

repeated again at 10:01:43.889, 10:07:43.828: Last log entry repeated for 21 more lines, and again after every scene change. Then OBS video glitched for a few seconds and the audio being sent by track 6 had what seemed like a 3-5 second delay (as seen in the meters being recorded from a screen capture of Wave Link). Spoke into microphone, stop. Noticed meters move on output device after stopped speaking. Looking at the log file shows:

10:45:37.799: adding 533 milliseconds of audio buffering, total audio buffering is now 917 milliseconds (source: RE20-Left)
10:45:37.799: 
10:45:39.361: Max audio buffering reached!
10:45:39.361: adding 42 milliseconds of audio buffering, total audio buffering is now 960 milliseconds (source: FX-GTA V Wasted 2.0 - Camera Clone)
10:45:39.361: 

So when max audio buffering was reached, OBS glitched the recorded video, but playback of the recording has main audio keep working during the video glitch. However the Audio Monitor output on track 6 had a delay ?? equivalent to the time the video glitched out ?? 

Uploaded Crash log can be found here: https://obsproject.com/logs/IU4kZziNOAqBs6Dm
Uploaded OBS log can be found here: https://obsproject.com/logs/daon37UfyMZGZo3C

**Comment by exeldro** [comment]
2. will be fixed with version 0.8.6
